// <auto-generated />
namespace University_For_All.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adddatatocourses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddatatocourses));
        
        string IMigrationMetadata.Id
        {
            get { return "202012171905143_adddatatocourses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
